# Generated by Django 2.1.7 on 2019-07-02 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('11', 'A'), ('12', 'B'), ('13', 'C'), ('21', 'D'), ('22', 'E'), ('31', 'F'), ('32', 'G')], max_length=50)),
                ('issue_date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('studentimage', models.ImageField(null=True, upload_to='studentimage')),
            ],
        ),
        migrations.AddField(
            model_name='lib',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
    ]
